language: generic
sudo: required
services:
  - docker

before_install: 
  - docker build -t nguyen/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true nguyen/docker-react npm run test